language: node_js

node_js:
  - "node"
  - "lts/*"

branches:
  only:
    - master

notifications:
  email: false

install:
  - npm ci

cache:
  directories:
    - "node_modules"

script:
  - npm --version
  - npm run build
  - npm run test

after_success:
  - jest --coverage --coverageReporters=text-lcov | coveralls
