name: Coveralls

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  coveralls:
    name: coveralls
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies and make test-coverage
        run: |
          npm ci
          npm run coveralls

      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
