name: Npm Package Publish

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

# based on https://www.yuque.com/egg/nodejs/github-actions-release-enhance
jobs:
  publish-npm:
    runs-on: ubuntu-latest
    container:
      image: thonatos/github-actions-nodejs
    steps:
      - uses: actions/checkout@master
      - name: Install Dependencies
        run: |
          npm install -g npminstall
          npminstall
      - run: npm test
      - name: Release NPN Package
        run: npm run semantic-release
        env:
          NPM_TOKEN: ${{ secrets.NPM_PACKAGE_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

